CREATE TABLE `leads` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `status` TINYINT NOT NULL DEFAULT 1,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `company_name` VARCHAR(150) NULL,
  `job_title` VARCHAR(100) NULL,
  `email` VARCHAR(190) NOT NULL,
  `phone` VARCHAR(30) NULL,
  `mobile_phone` VARCHAR(30) NULL,
  `website` VARCHAR(190) NULL,
  `address` VARCHAR(190) NULL,
  `city` VARCHAR(100) NULL,
  `postal_code` VARCHAR(10) NULL,
  `stage` VARCHAR(50) NOT NULL,
  `priority` TINYINT UNSIGNED NULL,
  `estimated_value` DECIMAL(10,2) NULL,
  `assigned_user_id` INT UNSIGNED NULL,
  `next_follow_up_at` DATE NULL,
  `last_contacted_at` DATETIME NULL,
  `lost_reason` VARCHAR(190) NULL,
  `converted_customer_id` INT UNSIGNED NULL,
  `converted_at` DATETIME NULL,
  `notes` TEXT NULL,
  `source_channel` VARCHAR(50) NULL,
  `campaign` VARCHAR(100) NULL,
  `keyword` VARCHAR(100) NULL,
  `landing_page` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `created_by` INT UNSIGNED NULL,
  `updated_at` DATETIME NULL,
  `updated_by` INT UNSIGNED NULL,
  CONSTRAINT `fk_leads_assigned_user_id` FOREIGN KEY (`assigned_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_leads_converted_customer_id` FOREIGN KEY (`converted_customer_id`) REFERENCES `customers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

