<?php

declare(strict_types=1);

use App\Prompt\PromptToolRegistry;
use App\Prompt\Tool\EditAppointmentTool;
use App\Prompt\Tool\EditBlogPostTool;
use App\Prompt\Tool\EditCampaignTool;
use App\Prompt\Tool\EditCaseTool;
use App\Prompt\Tool\EditCommunicationTool;
use App\Prompt\Tool\EditCustomerTool;
use App\Prompt\Tool\EditDocumentRequestTool;
use App\Prompt\Tool\EditInterventionTool;
use App\Prompt\Tool\EditInvoiceTool;
use App\Prompt\Tool\EditLeadTool;
use App\Prompt\Tool\EditPermissionTool;
use App\Prompt\Tool\EditProductTool;
use App\Prompt\Tool\EditRefundTool;
use App\Prompt\Tool\EditServiceTool;
use App\Prompt\Tool\EditTaskTool;
use App\Prompt\Tool\EditUserTool;
use App\Prompt\Tool\InstallPackageTool;
use App\Prompt\Tool\ListAppointmentsTool;
use App\Prompt\Tool\ListBlogPostsTool;
use App\Prompt\Tool\ListCampaignsTool;
use App\Prompt\Tool\ListCasesTool;
use App\Prompt\Tool\ListCommunicationsTool;
use App\Prompt\Tool\ListCustomersTool;
use App\Prompt\Tool\ListDocumentRequestsTool;
use App\Prompt\Tool\ListInterventionsTool;
use App\Prompt\Tool\ListInvoicesTool;
use App\Prompt\Tool\ListLeadDuplicatesTool;
use App\Prompt\Tool\ListLeadsTool;
use App\Prompt\Tool\ListMessageTemplatesTool;
use App\Prompt\Tool\EditMessageTemplateTool;
use App\Prompt\Tool\ListPackagesTool;
use App\Prompt\Tool\ListPermissionsTool;
use App\Prompt\Tool\ListProductsTool;
use App\Prompt\Tool\ListRefundsTool;
use App\Prompt\Tool\ListServicesTool;
use App\Prompt\Tool\ListTasksTool;
use App\Prompt\Tool\ListUsersTool;
use App\Prompt\Tool\ShowHomeDashboardTool;
use App\Prompt\Tool\ShowMenuTool;
use App\Prompt\Tool\ShowAgentsTool;
use App\Prompt\Tool\ShowProjectsTool;
use App\Prompt\Tool\ShowReportTool;
use App\Prompt\Tool\ShowSetupTool;
use App\Prompt\Tool\ShowWizardTool;

return static function (PromptToolRegistry $registry): void {
    // Prima usato solo da IndexController per la home vera e propria -
    // registrato anche qui perche' il pulsante "casa" della toolbar del
    // prompt (vedi hero.js) lo raggiunge tramite window.unoSubmitPrompt
    // ('home'), che passa sempre da matchLocalTool() su questo registro.
    $registry->register(ShowHomeDashboardTool::class, 'leads', 'cases', 'document_requests', 'tasks', 'refunds');
    $registry->register(ShowMenuTool::class);
    $registry->register(ShowWizardTool::class);
    $registry->register(ListUsersTool::class);
    $registry->register(ListPermissionsTool::class);
    $registry->register(ListLeadsTool::class, 'leads');
    $registry->register(ListLeadDuplicatesTool::class, 'leads');
    $registry->register(ListCustomersTool::class, 'customers', 'cases', 'leads', 'refunds', 'document_requests');
    $registry->register(ListTasksTool::class, 'tasks');
    $registry->register(ListAppointmentsTool::class, 'appointments');
    $registry->register(ListProductsTool::class, 'catalog');
    $registry->register(ListServicesTool::class, 'services');
    $registry->register(ListInterventionsTool::class, 'interventions');
    $registry->register(ListBlogPostsTool::class, 'blog');
    $registry->register(ListCampaignsTool::class, 'campaigns');
    $registry->register(ListInvoicesTool::class, 'invoices');
    $registry->register(ListCasesTool::class, 'cases');
    $registry->register(ListDocumentRequestsTool::class, 'document_requests');
    $registry->register(ListCommunicationsTool::class, 'communications');
    $registry->register(ListRefundsTool::class, 'refunds');
    $registry->register(EditUserTool::class);
    $registry->register(EditPermissionTool::class);
    $registry->register(EditLeadTool::class, 'leads');
    $registry->register(EditCustomerTool::class, 'customers');
    $registry->register(EditTaskTool::class, 'tasks');
    $registry->register(EditAppointmentTool::class, 'appointments');
    $registry->register(EditProductTool::class, 'catalog');
    $registry->register(EditServiceTool::class, 'services');
    $registry->register(EditInterventionTool::class, 'interventions');
    $registry->register(EditBlogPostTool::class, 'blog');
    $registry->register(EditCampaignTool::class, 'campaigns');
    $registry->register(EditInvoiceTool::class, 'invoices');
    $registry->register(EditCaseTool::class, 'cases');
    $registry->register(EditDocumentRequestTool::class, 'document_requests');
    $registry->register(EditCommunicationTool::class, 'communications');
    $registry->register(EditRefundTool::class, 'refunds');
    $registry->register(ListMessageTemplatesTool::class, 'message_templates');
    $registry->register(EditMessageTemplateTool::class, 'message_templates');
    $registry->register(ListPackagesTool::class, 'provisioning');
    $registry->register(InstallPackageTool::class, 'provisioning');
    $registry->register(ShowReportTool::class, 'leads', 'cases', 'document_requests', 'communications', 'tasks', 'refunds');
    $registry->register(ShowSetupTool::class, 'connectors', 'message_templates');
    $registry->register(ShowAgentsTool::class, 'agents', 'leads', 'cases', 'document_requests', 'communications', 'refunds');
    $registry->register(ShowProjectsTool::class, 'provisioning');
};
